import React from "react";
import Head from "next/head";
import Header from "./Header";
import Footer from "./Footer";

interface Props {
  children?: React.ReactNode;
  id?: string;
  title?: string;
  description?: string;
}

export default function Main({ children, id, title, description }: Props) {
  return (
    <div id={id}>
      <Head>
        <title>{title}</title>
        <meta
          name="description"
          content={description ? description : "Generated by create next app"}
        />
      </Head>
      <div>
        <Header/>
        <main>{children}</main>
        <Footer/>
      </div>
    </div>
  );
}
