import React from "react";
import Head from "next/head";
import Header from "./Header";
import Footer from "./Footer";
import { Box } from "@mui/material";

interface Props {
  children?: React.ReactNode;
  id?: string;
  title?: string;
  description?: string;
  links: Array<{ link: string; label: string }>;
}

export default function Main({
  children,
  id,
  title,
  description,
  links,
}: Props) {
  return (
    <Box
      sx={{ borderTop: (theme) => `1px solid ${theme.palette.grey[400]}` }}
      px={3}
      id={id}
    >
      <Head>
        <title>{title}</title>
        <meta
          name="description"
          content={description ? description : "Generated by create next app"}
        />
      </Head>
      <Box>
        <Header links={links} title={title} />
        <Box component="main" p={2}>
          {children}
        </Box>
        <Footer />
      </Box>
    </Box>
  );
}
